22308 - Fix issue converting map attributes containing list attribute…
3mcloud/falcano pull request #24
Opened 2020-10-12 14:04 UTC by jjf130

…s when fetched from dynamo

2020-10-12 15:47 UTC, erictwalker18 requested changes

2020-10-12 15:47 UTC, erictwalker18 commented on tests/unit/test_map_attribute.py
> +os.environ['AWS_ACCESS_KEY_ID'] = 'my-access-key'
use monkeypatch for env vars

```python
def test_something(monkeypatch):
    monkeypatch.setenv('SOMETHING', 'value')
```

2020-10-12 15:47 UTC, erictwalker18 commented on tests/unit/test_map_attribute.py
> +    create_dict = {
Move this to integration tests

2020-10-12 18:24 UTC, jjf130 commented on tests/integration/test_map_attribute.py
> +        table_name = 'falcano-map-attr-e2e'
changed this so that the integration tests in test_model.py don't fail

2020-10-12 18:42 UTC, mneil requested changes

2020-10-12 18:42 UTC, mneil commented on tests/integration/test_map_attribute.py
> +                {'mid_map': {'M': {'baz': 'qux', 'lst': {'L': ['blah']}}}},
This isn't what we want. We expect this to be a deserialized map without the types 'M' or 'L'

2020-10-12 22:45 UTC, mneil approved these changes

2020-10-13 17:15 UTC, erictwalker18 requested changes

2020-10-13 17:15 UTC, erictwalker18 commented on Makefile
> +
Remove extra newline

2020-10-13 17:15 UTC, erictwalker18 commented on falcano/attributes.py
> +            rval.append({attr_key: attr_class.serialize(val)})
Doesn't this break other serialization when we don't want the dynamodb json?

2020-10-13 17:42 UTC, erictwalker18 commented on falcano/attributes.py
> +            rval.append({attr_key: attr_class.serialize(val)})
Turns out, it doesn't break things like `save()` whether you have the dynamodb json in it or not

2020-10-13 17:45 UTC, erictwalker18 approved these changes
LGTM

2020-10-13 17:45 UTC, merged