Make paginator run iteratively
3mcloud/falcano pull request #48
Opened 2021-12-09 22:07 UTC by sukritsangvong

- Made `paginator.py` run iteratively
- Created `paginator_test.py` to check if the iteration solves RecursionDepthError
- Updated `batch.md` to include more information

2021-12-13 20:08 UTC, erictwalker18 requested changes
Good work, neaten up a couple things

2021-12-13 20:08 UTC, erictwalker18 commented on tests/integration/test_paginator.py
> +                batch.save(person)
smallperson is redundant since there are only 5 elements in there. Probably move that to the test_reset method

2021-12-13 20:08 UTC, erictwalker18 commented on tests/integration/test_paginator.py
> +        while primary < 101:
This will create and add 100 people for every test in this class - given that it's only needed for test_paginator_for_recursion_depth, make it a [setUpClass](https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUpClass) or put the creation of items into the test itself.

2021-12-13 20:08 UTC, erictwalker18 commented on tests/integration/test_paginator.py
> +
Missing trailing newline?

2021-12-13 20:08 UTC, erictwalker18 commented on tests/integration/test_paginator.py
> +        except RecursionError:
Technically, you don't need this. If it throws an error, pytest will tell you what it was. Also it's `recursion limit+1` data

2021-12-14 20:53 UTC, sukritsangvong commented on tests/integration/test_paginator.py
> +        except RecursionError:
fixed with 2c72426

2021-12-14 20:53 UTC, sukritsangvong commented on tests/integration/test_paginator.py
> +
fixed with 791e153

2021-12-14 20:53 UTC, sukritsangvong commented on tests/integration/test_paginator.py
> +        while primary < 101:
fixed with e2ed6b1

2021-12-14 20:53 UTC, sukritsangvong commented on tests/integration/test_paginator.py
> +                batch.save(person)
Not exactly sure what this means. Can you please clarify?

2021-12-14 21:06 UTC, erictwalker18 commented on tests/integration/test_paginator.py
> +                batch.save(person)
SmallPerson isn't necessarily required, and it does add unnecessary complexity. SmallPerson and Person are essentially identical. So for the reset test, just use Person objects.

Also we don't need SmallPeople (or whatever we create) created for every test, just the test_reset - so move the code that creates these to the test_reset method

2021-12-14 21:15 UTC, sukritsangvong commented on tests/integration/test_paginator.py
> +                batch.save(person)
fixed with f295e77

2021-12-15 15:42 UTC, erictwalker18 approved these changes
Great work!

2021-12-15 17:50 UTC, merged